# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '@types/vscode'  # needs to match engines.vscode
    groups:
      vsce:
        dependency-type: development
        patterns:
          - '@vscode/vsce'
          - '@secretlint/*'
